Changed tables
YuliiaManivska/Internship pull request #2
Opened 2021-12-15 20:39 UTC by YuliiaManivska

2021-12-15 21:07 UTC, olehvavryniv requested changes

2021-12-15 21:07 UTC, olehvavryniv commented on lesson5/app/models/patient.rb
> +    message "%{value} is not a valid" }
I think you forgot `:`. Should be `message: "....`

2021-12-15 21:07 UTC, olehvavryniv commented on lesson5/app/models/patient.rb
> +  has_many :physicians, through: :diagnosis_items
You duplicated `has_many :physicians`. It is an error.

2021-12-15 21:07 UTC, olehvavryniv commented on lesson5/app/models/physician.rb
> +  has_many :patients, through: :diagnosis_items
Same here. Line duplication.

2021-12-15 21:07 UTC, olehvavryniv commented on lesson5/db/migrate/20211215130320_add_columns_to_tables.rb
> +      t.column :last_name, :string
You forgot NOT NULL constraints.

2021-12-15 21:07 UTC, olehvavryniv commented on lesson5/db/migrate/20211215130320_add_columns_to_tables.rb
> +      t.timestamps
Where are the references? physician_id and patient_id

2021-12-17 13:54 UTC, YuliiaManivska commented
@olehvavryniv please, check

2021-12-27 10:38 UTC, olehvavryniv approved these changes

2021-12-27 11:04 UTC, merged